### ISSUE TITLE
Feature request: Filter users

### ISSUE THREAD

**Issue by jwtue** [cdaecke/md_saml#20]
Hi, great work so far.

I was wondering if you could add a feature to filter users when authenticating, especially for backend.

Like, only users having a certain group in their SSO-provided group list may login into backend.

(In my use case, all users should be able to log into frontent, but only some are allowed into backend.)

Thank you!

**Comment by cdaecke** [comment]
Hi,

thanks for your input.

From my point of view this is not necessary, since you can configure the ADFS server, which users can access the SSO config there.

Since you need to have two configurations in the ADFS server, one for the backend login and one for the frontend login, you can configure different users there.

Does this answer your question?
