### ISSUE TITLE
User's data is not transferred to TYPO3

### ISSUE THREAD

**Issue by yoo-bub** [cdaecke/md_saml#4]
Good morning

I am using for a POC of a customer their extension "md_saml". It has been a long time since I did anything in TYPO3, but I assume that the settings are all correct.

When I click the button on the login page, it takes me to the Azure service where I can do the login. This all works and it also seems to send data back, which is evident in the screenshot, however it does not process the data and is not logged into the TYPO3 frontend.

This is a standard TYPO3 installation with the Introduction Package.

Do you have any idea why it does not process the user data after coming back to the page? According to my settings, it should create a new user when it does not exist.

About a short feedback I would be very grateful to them.
Wish you a good start into the new week.

Best regards
Björn Bühler
[Archiv.zip](https://github.com/cdaecke/md_saml/files/10838009/Archiv.zip)

**Comment by cdaecke** [comment]
Please try to set the following configuration to `false`:

https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L71

**Comment by georggood** [comment]
> Please try to set the following configuration to `false`:
> 
> https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L71

The `strict = false` option did not help. What else can be done to get the user's email from Azure AD?

**Comment by tetrispt** [comment]
Hi,

Thanks for creating this great extension.

I have the same problem with user's data transfer. The user nevers login.

Please find in attach my conf file setup.typoscript

Thanks in advance for any feedback!

Best Regards

[my_setup_typoscript.zip](https://github.com/cdaecke/md_saml/files/11212459/my_setup_typoscript.zip)

**Comment by tetrispt** [comment]
> > Please try to set the following configuration to `false`:
> > https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L71
> 
> The `strict = false` option did not help. What else can be done to get the user's email from Azure AD?

Did you get any error?

**Comment by georggood** [comment]
**Do you have any idea why it does not process the user data after coming back to the page? According to my settings, it should create a new user when it does not exist.**

The code file lacks initialization of the username field: .../md_saml/Classes/Authentication/SamlAuthService.php

Now the code without initialization:

```
                $samlAttributes = $auth->getAttributes();
                $user = $this->getUserArrayForDb($samlAttributes, $extSettings);

                $record = $this->fetchUserRecord($user['username']);
                if (is_array($record)) {
                    return $record;
                } elseif ($extSettings[$this->authInfo['db_user']['table']]['createIfNotExist'] == 1) {
                    return $this->createUser($user);
                }

```
I did like this:

 ```
               $samlAttributes = $auth->getAttributes();
                $user = $this->getUserArrayForDb($samlAttributes, $extSettings);

                if (strcmp($auth->getNameIdFormat(), 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress') == 0) {
                    $user['username'] = $auth->getNameId();
                    $user['email'] = $auth->getNameId();
                    $user['realName'] = $auth->getNameId();
                }
                $record = $this->fetchUserRecord($user['username']);
                if (is_array($record)) {
                     return $record;
                } elseif ($extSettings[$this->authInfo['db_user']['table']]['createIfNotExist'] == 1) {
                    return $this->createUser($user);
                }

```

**Comment by tetrispt** [comment]
It didn't work for me...

I'm using for users store / Protected Area Members  the configuration available on the video:

https://www.youtube.com/watch?v=SJU3-UszJSs

The SAML authenticate the user and redirect to the page:
https://www.demo120.pt/login-page/?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs&logintype=login

But, the user didn't log in!

Could you share your setup.typoscript ? 

Thanks for any help.

**Comment by georggood** [comment]
> But, the user didn't log in!

The video shows authorization on FE, I have an authorization solution in BE.
My setup.typoscript won't help you.
But I want to help you. Since the extension works for me, after I made a few corrections in the code.
Questions: Have you configured to receive errors in the extension?
Do you have `debug = true` enabled?
If you have correctly configured to receive errors, then you can receive validation error messages (I had two of them). See the result of the function:
`public function isValid($requestId = null)` in file //typo3conf/ext/md_saml/Resources/Libraries/vendor/onelogin/php-saml/src/Saml2/Response. php

Give your request attributes and responses a look. You may not be sending or receiving correct data. You also need to correctly make the settings in Azure.

But you need correct information where you have a problem.
I fixed a lot and made a lot of adjustments until the user started doing authorization correctly. Even an incorrect group ID can cause registration failure. See settings:
```
databaseDefaults {
        pid = 1
        usergroup = 1
      }
```

**Comment by cdaecke** [comment]
Like @georggood said, you need to adapt the settings to your needs:

Backend users:
https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L19-L23

Frontend users:
https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L48-L54

Make sure, that you have configured the ADFS server:
https://github.com/cdaecke/md_saml#adfs

Check, what you get back when submitting the login form. Add `\TYPO3\CMS\Core\Utility\DebugUtility::debug($samlAttributes); exit;` right after this line:
https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Classes/Authentication/SamlAuthService.php#L130

@georggood  Be careful with changing the code, because it will get lost, after updating the extension.
